console.log("hihi");
console.log("출력");
var number = 24;
console.log("number는 %d 입니다.", number);
console.log("number는 " + number + "입니다.");
var message = "안녕하세여ㅕㅕ";
console.log("message는 %s 입니다.", message);
console.log("message는 " + message + "입니다.");
var json = {jj:"json입니다."};
console.log("Json 출력 : %j", json);
console.log("Json 속성 출력 : %s", json.jj);